module.exports = {
  apps: [
    {
      name: 'wallet_user',
      script: './dist/main.js',
      exec_mode: 'cluster',
      cwd: './services/wallet_user/',
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: 3000,
        PSQL_DATABASE: 'g-messenger',
        PSQL_HOST: 'localhost',
        PSQL_PORT: 5555,
        PSQL_USERNAME: 'user',
        PSQL_PASSWORD: 'secret',
        ADMINER_PORT: 5556,
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
        REDIS_PASSWORD: 'untWGJVQUNnngj',
        ACCESS_TOKEN_KEY: 'access-token-key',
        REFRESH_TOKEN_KEY: 'refresh-token-key',
        ACCESS_TOKEN_EXPIRES_IN: '7d',
        REFRESH_TOKEN_EXPIRES_IN: '10d',
        SALT: 'SALT',
        IMAGE_SIZE: 10,
        VIDEO_SIZE: 100,
        AUDIO: 10,
        APPLICATION: 10,
        S3_ACCESS_KEY: 'J2yvraGmbvtyeYYtPE2qm',
        S3_SECRET_KEY: 'bx7KyD2KBGyakaVfjeu86i3Ltk2KegLqzoidN6QztJ1o',
        S3_ENDPOINT: 'https://hb.bizmrg.com',
        S3_REGION: 'ru-msk',
        S3_BUCKET_NAME: 'g-messenger',
        S3_URL: 'https://g-messenger.hb.bizmrg.com',
      },
      output: './logs/wallet_user/output.log',
      error: './logs/wallet_user/error.log',
      log: './logs/wallet_user/combined.outerr.log',
    },
  ],
}
