export enum ChatEventsEnum {
  CREATE_CHAT = 'create-chat',
  IS_EXIST_CHAT = 'is-exist-chat',
  CREATED_CHAT = 'created-chat',
  LEAVE_GROUP = 'leave-group',
  LEFT_GROUP = 'left-group',
  IS_NOT_READ_MESSAGES_COUNT = 'is-not-read-messages-count',
  CREATE_MESSAGE_ERROR = 'create-message-error',
  CREATE_MESSAGE = 'create-message',
  CREATED_MESSAGE = 'created-message',
  DELETE_MESSAGE = 'delete-chat',
  DELETED_MESSAGE = 'deleted-message',
  INVITE_USER = 'invite-user',
  INVITE_SENT = 'invite-sent',
  INVITE_ERROR = 'invite-error',
  ACCEPT_INVITE = 'accept-invite',
  REJECT_INVITE = 'reject-invite',
  ANSWER_ON_INVITE = 'answer-on-invite',
}
