export enum ChatEventsDescriptionsEnum {
  CREATE_DIALOG_CHAT = 'Cоздать диалог с пользователем',
  CREATED_CHAT = 'Получить созданный чат',
  CREATE_GROUP_CHAT = 'Создать групповой чат с пользователями',
  CREATED_MESSAGE = 'Получить созданное сообщение',
  EDITED_MESSAGE = 'Получить отредактированное сообщение',
  DELETED_MESSAGE = 'Получить удаленное сообщение',
  CREATE_MESSAGE = 'Cоздать сообщение',
  EDIT_MESSAGE = 'Редактировать сообщение',
  DELETE_MESSAGE = 'Удалить сообщение',
  READ_MESSAGES = 'Прочитать сообщениия',
  READED_MESSAGES = 'Получить прочитанные сообщения',
  TYPING_MESSAGE = 'Отправить информациию о том, что пользователь печатает текст',
  USER_TYPING_MESSAGE = 'Получить информацию о том, какой пользователь сейчас печатает сообщение и в каком чате',
  ACTIVATE_CHAT = 'Активировать чат',
  DELETE_CHAT = 'Удалить чат',
  CLEAR_CHAT = 'Очистить чат',
  UPDATED_CHAT = 'Получить обновленный чат',
  DELETED_CHAT = 'Получить удаленный чат',
  CLEARED_CHAT = 'Получить очищенный чат',
  BLOCK_CHAT = 'Заблокировать чат',
  CHANGE_STATUSES_MESSAGES = 'Изменить статус у сообщений',
  CHANGED_STATUSES_MESSAGES = 'Получить сообщения с новым статусом',
  ACTIVE_CHATS = 'Получить активные чаты пользователя',
  REQUEST_CHATS = 'Получить запросы на общение с пользователем',
  UNREADED_CHATS_COUNT = 'Получить количество чатов с непрочитанными сообщениями',
}
