version: '3.8'

networks:
  g-messenger:
    name: g-messenger

services:
  adminer:
    image: adminer
    container_name: g-messenger-adminer
    networks:
      - g-messenger
    environment:
      ADMINER_PLUGINS: tables-filter tinymce
      ADMINER_DESIGN: lucas-sandery
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3-alpine
    container_name: g-messenger-postgres
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    networks:
      - g-messenger
    volumes:
      - ../runtime/postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    restart: always
    ports:
      - ${PSQL_PORT}:5432

  redis:
    image: redis:7.0.5
    restart: always
    container_name: g-messenger-redis
    command: redis-server --port ${REDIS_PORT} --appendonly yes --replica-read-only no
    networks:
      - g-messenger
    volumes:
      - ../runtime/redis:/bitnami/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379

  api:
    container_name: g-messenger-api
    networks:
      - g-messenger
    build:
      context: ../.
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 16G

